# nginx 이미지를 지정
nginx:
    build: ./nginx

    # nginx컨테이너는 node컨테이너를 연결
    links:
        - node 
    ports:
        - "80:80"

# node 이미지를 지정
node:
    build: ./node

    # node컨테이너는 mongodb컨테이너를 연결
    links:
        - mongodb:db_url
    ports:
        - "3000"

mongodb:
    image: mongo
    ports:
        - "27017"
    
    # 컨테이너를 내렸다 올릴때 데이터베이스도 초기화
    # volume을 지정해서 데이터 유지
    volumes: 
        - /data/db

